apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-postgres-pvc
  namespace: postgress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi     
  storageClassName: standard   # or your GKE storage class
